# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/ui', 'ui'),
        ('src/excel_to_sql', 'excel_to_sql'),
        ('src/utils', 'utils'),
        ('data/quotation_template.xlsx', 'data'),
        ('prices.db', '.'),
        ('assets', 'assets')
    ],
    hiddenimports=[
        'ui.quotation_ui',
        'utils.price_calculator',
        'utils.sql_loader',
        'utils.equation_parser',
        'utils.filter_utils',
        'utils.product_utils',
        'utils.quote_utils',
        'utils.excel_exporter',
        'utils.excel_importer',
        'excel_to_sql.getsql',
        'excel_to_sql.handlers.default_handler',
        'excel_to_sql.handlers.header_handler', 
        'excel_to_sql.handlers.other_handler',
        'sqlite3',
        'openpyxl'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'tkinter',
        'PIL',
        'cv2',
        'torch',
        'torchvision',
        'sklearn',
        'skimage',
        'tensorflow',
        'keras',
        'h5py',
        'sympy',
        'jinja2',
        'pygments',
        'imageio',
        'psutil',
        'setuptools',
        'distutils',
        'pkg_resources',
        'packaging',
        'certifi',
        'charset_normalizer',
        'requests',
        'urllib3',
        'werkzeug',
        'cpuinfo',
        'appdirs'
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='QuoteFlow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
app = BUNDLE(
    exe,
    name='QuoteFlow.app',
    icon='assets/icon.icns',
    bundle_identifier=None,
)
