name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Pillow installation
      run: |
        python -c "import PIL; print('Pillow version:', PIL.__version__)"
        python -c "from PIL import Image; print('PIL Image module available')"

    - name: Verify icon files exist
      run: |
        dir assets\
        Get-ChildItem assets\icon.ico

    - name: Build executable
      run: |
        pyinstaller QuoteFlow.spec

    - name: Sign Windows executable (optional)
      if: false # Set to true if you have a code signing certificate
      run: |
        # Add code signing here if you have a certificate
        # signtool sign /f "certificate.pfx" /p "password" /t "http://timestamp.digicert.com" dist/QuoteFlow.exe

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: QuoteFlow-Windows
        path: dist/QuoteFlow.exe
        retention-days: 30

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-windows
        path: |
          build/
          *.log
        retention-days: 7
