name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Pillow installation
      run: |
        python -c "import PIL; print('Pillow version:', PIL.__version__)"
        python -c "from PIL import Image; print('PIL Image module available')"

    - name: Verify icon files exist
      run: |
        dir assets\
        Get-ChildItem assets\icon.ico

    - name: Generate ICO file
      run: |
        python -c "
        from PIL import Image, ImageDraw
        import os

        def add_rounded_corners(image, radius=200):
            mask = Image.new('L', image.size, 0)
            draw = ImageDraw.Draw(mask)
            draw.rounded_rectangle([0, 0, image.size[0], image.size[1]], radius=radius, fill=255)
            output = Image.new('RGBA', image.size, (0, 0, 0, 0))
            output.paste(image, mask=mask)
            return output

        # Open and process the PNG
        img = Image.open('assets/icon.png')
        img = img.convert('RGBA')
        rounded_img = add_rounded_corners(img, radius=200)

        # Create a 256x256 ICO file (most important size for Windows)
        resized = rounded_img.resize((256, 256), Image.LANCZOS)
        resized.save('assets/icon.ico', format='ICO')

        print(f'Generated ICO file')
        print(f'File size: {os.path.getsize("assets/icon.ico")} bytes')

        # Test if it works
        try:
            test_img = Image.open('assets/icon.ico')
            print(f'ICO test: {test_img.size}, {test_img.mode} - SUCCESS!')
        except Exception as e:
            print(f'ICO test failed: {e}')
        "

    - name: Build executable
      run: |
        pyinstaller QuoteFlow.spec

    - name: Sign Windows executable (optional)
      if: false # Set to true if you have a code signing certificate
      run: |
        # Add code signing here if you have a certificate
        # signtool sign /f "certificate.pfx" /p "password" /t "http://timestamp.digicert.com" dist/QuoteFlow.exe

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: QuoteFlow-Windows
        path: dist/QuoteFlow.exe
        retention-days: 30

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-windows
        path: |
          build/
          *.log
        retention-days: 7
