name: Build All Platforms

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate ICO file
      run: |
        python -c "
        from PIL import Image, ImageDraw
        import os

        def add_rounded_corners(image, radius=200):
            mask = Image.new('L', image.size, 0)
            draw = ImageDraw.Draw(mask)
            draw.rounded_rectangle([0, 0, image.size[0], image.size[1]], radius=radius, fill=255)
            output = Image.new('RGBA', image.size, (0, 0, 0, 0))
            output.paste(image, mask=mask)
            return output

        img = Image.open('assets/icon.png').convert('RGBA')
        rounded_img = add_rounded_corners(img, radius=200)
        resized = rounded_img.resize((256, 256), Image.LANCZOS)
        resized.save('assets/icon.ico', format='ICO')
        print('Generated ICO file:', os.path.getsize('assets/icon.ico'), 'bytes')
        "

    - name: Build Windows executable
      run: pyinstaller QuoteFlow.spec

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: QuoteFlow-Windows
        path: dist/QuoteFlow.exe
        retention-days: 30

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build macOS application
      run: pyinstaller QuoteFlow.spec

    - name: Package .app bundle for upload
      run: |
        cd dist
        zip -r QuoteFlow-macOS.zip QuoteFlow.app

    - name: Upload macOS application
      uses: actions/upload-artifact@v4
      with:
        name: QuoteFlow-macOS
        path: dist/QuoteFlow-macOS.zip
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Linux executable
      run: pyinstaller QuoteFlow.spec

    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: QuoteFlow-Linux
        path: dist/QuoteFlow
        retention-days: 30
